# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-02 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0008_auto_20151120_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archiveddropboxsite',
            name='dropbox_hash',
        ),
        migrations.RemoveField(
            model_name='dropboxsite',
            name='dropbox_hash',
        ),
        migrations.AddField(
            model_name='dropboxsite',
            name='cursor',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
