# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-06 15:46
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0009_auto_20151202_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiveddropboxsite',
            name='config',
            field=jsonfield.fields.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='dropboxsite',
            name='config',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
