# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0010_auto_20151206_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropboxuser',
            name='user_id',
            field=models.CharField(max_length=64, unique=True, verbose_name='user id'),
        ),
    ]
