# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-12 14:09
from __future__ import unicode_literals

from django.db import migrations

import uuid


def gen_unique_account_id(apps, schema_editor):
    DropboxUserModel = apps.get_model('console', 'DropboxUser')

    for row in DropboxUserModel.objects.all():
        row.account_id = uuid.uuid1()
        row.save()


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0012_dropboxuser_account_id'),
    ]

    operations = [
        migrations.RunPython(gen_unique_account_id,
                             reverse_code=migrations.RunPython.noop),
    ]
