# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0014_auto_20151212_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropboxuser',
            name='account_id',
            field=models.CharField(max_length=64, verbose_name='account id'),
        ),
    ]
